config {
  type: "table",
  schema: "thelook_ecommerce_launch_demo",
  description: "Cleaned order data from thelook_ecommerce",
  columns: {
    order_id: "The unique ID of the order.",
    user_id: "The ID of the user who placed the order.",
    status: "The status of the order.",
    gender: "The gender of the user who placed the order.",
    created_at: "The timestamp when the order was created.",
    returned_at: "The timestamp when the order was returned.",
    shipped_at: "The timestamp when the order was shipped.",
    delivered_at: "The timestamp when the order was delivered.",
    num_of_item: "The number of items in the order."
  }
}

WITH cleaned_orders AS (
  SELECT
    CAST(order_id AS STRING) AS order_id,
    CAST(user_id AS STRING) AS user_id,
    COALESCE(status, 'Unknown') AS status,
    gender,
    created_at,
    returned_at,
    shipped_at,
    delivered_at,
    num_of_item
  FROM
    ${ref("orders_source")}
)
SELECT
  *
FROM
  cleaned_orders
QUALIFY ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY created_at DESC) = 1
